// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/*";
  };
  "pages/layouts/HomeLayout.tsx": {
    id: "pages/layouts/HomeLayout";
    page: "/";
  };
  "pages/HomeScreen.tsx": {
    id: "pages/HomeScreen";
    page: "/";
  };
  "pages/NotFound.tsx": {
    id: "pages/NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/layouts/HomeLayout": typeof import("./src/pages/layouts/HomeLayout.tsx");
  "pages/HomeScreen": typeof import("./src/pages/HomeScreen.tsx");
  "pages/NotFound": typeof import("./src/pages/NotFound.tsx");
};